reloadEnabled: true
language: 'en'
prefixFormat: '&7[&6MasterBuilders&7] '
topics:
  - Dog
  - Cat
  - Snake
  - Mouse
  - Ur Mom
offset: 5
build_time:
  - 5400
  - 2700
  - 1350
blacklisted_regions:
  - spawn